export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS" ;
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_PRESENT = "USER_PRESENT"

export const  GET_MENS_DATA="GET_MENS_DATA";
export  const  GET_MENS_REQUEST="GET_MENS_REQUEST";
export  const  GET_MENS_ERROR="GET_MENS_ERROR";

export  const  GET_WOMENS_REQUEST="GET_MENS_REQUEST";
export  const  GET_WOMENS_ERROR="GET_MENS_ERROR";
export const  GET_WOMENS_DATA="GET_WOMENS_DATA";

export  const  ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST";
export  const  ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS";
export const  ADD_TO_CART_ERROR="ADD_TO_CART_ERROR";

export  const  GET_CART_REQUEST="GET_CART_REQUEST";
export  const  GET_CART_SUCCESS="GET_CART_SUCCESS";
export const  GET_CART_ERROR="GET_CART_ERROR";

export  const  ADD_TO_WHITE_LIST_REQUEST="ADD_TO_WHITE_LIST_REQUEST";
export  const  ADD_TO_WHITE_LIST_SUCCESS="ADD_TO_WHITE_LIST_SUCCESS";
export const  ADD_TO_WHITE_LIST_ERROR="ADD_TO_WHITE_LIST_ERROR";

export  const  GET_WHITE_LIST_REQUEST="GET_WHITE_LIST_REQUEST";
export  const  GET_WHITE_LIST_SUCCESS="GET_WHITE_LIST_SUCCESS";
export const  GET_WHITE_LIST_ERROR="GET_WHITE_LIST_ERROR";




